#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MWF.Mobile.Android.Resource", IsApplication=true)]

namespace MWF.Mobile.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.String.ApplicationName = global::MWF.Mobile.Android.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.String.Hello = global::MWF.Mobile.Android.Resource.String.Hello;
			global::Splat.Resource.String.library_name = global::MWF.Mobile.Android.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::MWF.Mobile.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::MWF.Mobile.Android.Resource.String.Hello;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::MWF.Mobile.Android.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::MWF.Mobile.Android.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::MWF.Mobile.Android.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int GroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrowIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_clicked = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_unfocus = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Collect = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cross = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Deliver = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int drop_shadow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int empty_square = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_accept = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_call = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_camera = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_error = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_overflow = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_read = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_refresh = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_search = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_action_unread = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_warning = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_drawer_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int MessageWithPoint = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int mwf_logo = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ProceedFrom = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int proteo_mobile_white = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int proteoLogo = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int small_cross = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int splash = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int switch_bg_selector = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int switch_thumb_selector = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int tick = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int TrunkTo = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int warning = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060022
			public const int AdvanceButton = 2131099682;
			
			// aapt resource value: 0x7f06003f
			public const int BarcodeDamageStatus = 2131099711;
			
			// aapt resource value: 0x7f060001
			public const int BarcodeInput = 2131099649;
			
			// aapt resource value: 0x7f06003d
			public const int BarcodeItem = 2131099709;
			
			// aapt resource value: 0x7f060028
			public const int ButtonAddDeliveries = 2131099688;
			
			// aapt resource value: 0x7f06001a
			public const int ButtonAdvanceConfirmTimes = 2131099674;
			
			// aapt resource value: 0x7f060025
			public const int ButtonAdvanceInstructionComment = 2131099685;
			
			// aapt resource value: 0x7f06002c
			public const int ButtonAdvanceSignatureInstruction = 2131099692;
			
			// aapt resource value: 0x7f060030
			public const int ButtonChangeQuantity = 2131099696;
			
			// aapt resource value: 0x7f060003
			public const int ButtonCompleteScanning = 2131099651;
			
			// aapt resource value: 0x7f060038
			public const int ButtonNoTrailer = 2131099704;
			
			// aapt resource value: 0x7f06002a
			public const int ButtonSignatureToggle = 2131099690;
			
			// aapt resource value: 0x7f06001b
			public const int CustomerCodeBox = 2131099675;
			
			// aapt resource value: 0x7f060020
			public const int DoneButton = 2131099680;
			
			// aapt resource value: 0x7f060009
			public const int GridView = 2131099657;
			
			// aapt resource value: 0x7f060029
			public const int InstructionCustomerName = 2131099689;
			
			// aapt resource value: 0x7f060026
			public const int InstructionOnSiteListHeader = 2131099686;
			
			// aapt resource value: 0x7f060002
			public const int InstructionsLabel = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int MvxBindingTagUnique = 2131099648;
			
			// aapt resource value: 0x7f060031
			public const int OrderDetailLayout = 2131099697;
			
			// aapt resource value: 0x7f060045
			public const int SafetyCheckItem = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int SafetyCheckTitle = 2131099718;
			
			// aapt resource value: 0x7f060050
			public const int SafetyListView = 2131099728;
			
			// aapt resource value: 0x7f060052
			public const int action_refresh = 2131099730;
			
			// aapt resource value: 0x7f06001d
			public const int button = 2131099677;
			
			// aapt resource value: 0x7f060034
			public const int buttonCheckIn = 2131099700;
			
			// aapt resource value: 0x7f06000d
			public const int buttonCheckOut = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int buttonComplete = 2131099663;
			
			// aapt resource value: 0x7f060033
			public const int buttonPasscode = 2131099699;
			
			// aapt resource value: 0x7f06000c
			public const int buttonScanAgain = 2131099660;
			
			// aapt resource value: 0x7f060037
			public const int button_done = 2131099703;
			
			// aapt resource value: 0x7f06004f
			public const int checksdonebutton = 2131099727;
			
			// aapt resource value: 0x7f060021
			public const int clausedText = 2131099681;
			
			// aapt resource value: 0x7f06003a
			public const int clientRegistration = 2131099706;
			
			// aapt resource value: 0x7f060039
			public const int clientTitle = 2131099705;
			
			// aapt resource value: 0x7f060024
			public const int commentText = 2131099684;
			
			// aapt resource value: 0x7f060018
			public const int completeDatePicker = 2131099672;
			
			// aapt resource value: 0x7f060015
			public const int completeLinearLayout = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int completeTimePicker = 2131099673;
			
			// aapt resource value: 0x7f060051
			public const int contentFrame = 2131099729;
			
			// aapt resource value: 0x7f060005
			public const int doneButton = 2131099653;
			
			// aapt resource value: 0x7f060047
			public const int drawer_layout = 2131099719;
			
			// aapt resource value: 0x7f06000e
			public const int driverSignatureView = 2131099662;
			
			// aapt resource value: 0x7f060032
			public const int editTextPasscode = 2131099698;
			
			// aapt resource value: 0x7f060044
			public const int faultCheckComment = 2131099716;
			
			// aapt resource value: 0x7f060043
			public const int faultCheckTitle = 2131099715;
			
			// aapt resource value: 0x7f060040
			public const int faultImageView = 2131099712;
			
			// aapt resource value: 0x7f060048
			public const int fragment_host_main = 2131099720;
			
			// aapt resource value: 0x7f06004b
			public const int fragment_host_startup = 2131099723;
			
			// aapt resource value: 0x7f060008
			public const int imageComment = 2131099656;
			
			// aapt resource value: 0x7f06003b
			public const int instructionDate = 2131099707;
			
			// aapt resource value: 0x7f060027
			public const int instructionOnSiteHeader = 2131099687;
			
			// aapt resource value: 0x7f06003c
			public const int instructionTime = 2131099708;
			
			// aapt resource value: 0x7f06004e
			public const int instuctionList = 2131099726;
			
			// aapt resource value: 0x7f060042
			public const int itemText = 2131099714;
			
			// aapt resource value: 0x7f06004a
			public const int left_drawer = 2131099722;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout1 = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout2 = 2131099671;
			
			// aapt resource value: 0x7f060012
			public const int linearlayout4 = 2131099666;
			
			// aapt resource value: 0x7f060041
			public const int listHeader = 2131099713;
			
			// aapt resource value: 0x7f060006
			public const int logFaultTitleBlock = 2131099654;
			
			// aapt resource value: 0x7f06002e
			public const int odometerText = 2131099694;
			
			// aapt resource value: 0x7f060013
			public const int onSiteDatePicker = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int onSiteLinearLayout = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int onSiteTimePicker = 2131099668;
			
			// aapt resource value: 0x7f060023
			public const int openPhoneAppButton = 2131099683;
			
			// aapt resource value: 0x7f06001f
			public const int orderListView = 2131099679;
			
			// aapt resource value: 0x7f06004c
			public const int popUpAlertText = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int popUpImageView = 2131099725;
			
			// aapt resource value: 0x7f060049
			public const int relative_layout = 2131099721;
			
			// aapt resource value: 0x7f060035
			public const int reviseQuantityText = 2131099701;
			
			// aapt resource value: 0x7f06001c
			public const int safetyCheckFaults = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int scrollLayout = 2131099678;
			
			// aapt resource value: 0x7f06000b
			public const int selectFromLibrarytButton = 2131099659;
			
			// aapt resource value: 0x7f06002b
			public const int signature_instructionView = 2131099691;
			
			// aapt resource value: 0x7f060036
			public const int signature_view = 2131099702;
			
			// aapt resource value: 0x7f06003e
			public const int skinnyHamburger = 2131099710;
			
			// aapt resource value: 0x7f06002f
			public const int submit = 2131099695;
			
			// aapt resource value: 0x7f060004
			public const int swDelivered = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int takePictureButton = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int textView1 = 2131099655;
			
			// aapt resource value: 0x7f060016
			public const int textView2 = 2131099670;
			
			// aapt resource value: 0x7f06002d
			public const int trailerText = 2131099693;
			
			// aapt resource value: 0x7f060053
			public const int trailer_action_search = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int vehicle_action_search = 2131099732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Fragment_About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Fragment_Barcode = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Fragment_BarcodeStatus = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fragment_Camera = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Fragment_CheckIn = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Fragment_CheckInComplete = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Fragment_CheckOut = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Fragment_CheckOutQRCode = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Fragment_CheckOutSignature = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Fragment_ConfirmTimes = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Fragment_CustomerCode = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Fragment_Diagnostics = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Fragment_DisplaySafetyCheck = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Fragment_Inbox = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Fragment_Instruction = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Fragment_InstructionAddDeliveries = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Fragment_InstructionClaused = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Fragment_InstructionComment = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Fragment_InstructionOnSite = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Fragment_InstructionSignature = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Fragment_InstructionTrailer = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Fragment_InstructionTrunkProceed = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Fragment_Manifest = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Fragment_Message = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Fragment_Odometer = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Fragment_Order = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Fragment_Passcode = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Fragment_ReviseQuantity = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Fragment_SafetyCheckFaultView = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int Fragment_SafetyCheckSignature = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int Fragment_TermsAndConditions = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int Fragment_TrailerListView = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int Fragment_VehicleListView = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int Item_AddDelivery_Instruction = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int Item_Barcode = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int Item_Image = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int Item_Instruction = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int Item_Instruction_Order = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int Item_InstructionNotifcationHeader = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int Item_InstructionNotificationText = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int Item_InstructionOnSite_Order = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int item_menu = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int Item_Message = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int Item_SafetyCheck = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int Item_SafetyCheckFault = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int Item_SafetyCheckItem = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int Item_Section = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int Item_Spinner = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int Item_SpinnerDropDown = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int Item_Trailer = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int Item_Vehicle = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int Page_Main = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int Page_Startup = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int PopUp_Alert = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int PopUp_Image = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int PopUp_InstructionNotification = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int SafetyCheckView = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int SplashScreen = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int ZXingCustomLayout = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int zxingscanneractivitylayout = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int zxingscannerfragmentlayout = 2130903100;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int actionbar_indeterminate_progress = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int main_activity_actions = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int manifest_activity_actions = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int trailer_activity_actions = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int vehicle_activity_actions = 2131230724;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Kalimba = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int action_refresh = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int action_search = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int action_settings = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int application_name = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int drawer_close = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int drawer_open = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int library_name = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int Proteo = 2131165185;
			
			// aapt resource value: 0x7f070016
			public const int Proteo_Button = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int Proteo_Button_Bottom = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int Proteo_Button_InSection = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int Proteo_Button_NonBottom = 2131165210;
			
			// aapt resource value: 0x7f070017
			public const int Proteo_Button_Secondary = 2131165207;
			
			// aapt resource value: 0x7f07001b
			public const int Proteo_EditText = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int Proteo_EditText_Number = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int Proteo_EditText_NumberPasscode = 2131165212;
			
			// aapt resource value: 0x7f070021
			public const int Proteo_ImageView_InstructionIcon = 2131165217;
			
			// aapt resource value: 0x7f070020
			public const int Proteo_ImageView_MWFLogo = 2131165216;
			
			// aapt resource value: 0x7f07001e
			public const int Proteo_Multiline = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int Proteo_Multiline_Large = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int Proteo_SignaturePad = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int Proteo_Spinner = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int Proteo_Spinner_Text = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int Proteo_SpinnerDropdown_Text = 2131165222;
			
			// aapt resource value: 0x7f070023
			public const int Proteo_Switch_Text = 2131165219;
			
			// aapt resource value: 0x7f070015
			public const int Proteo_TextView_InfoAndInput = 2131165205;
			
			// aapt resource value: 0x7f070008
			public const int Proteo_TextView_Information = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int Proteo_TextView_Instructions = 2131165190;
			
			// aapt resource value: 0x7f070011
			public const int Proteo_TextView_ItemSectionHeading = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int Proteo_TextView_ItemText = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int Proteo_TextView_ItemText_Small = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int Proteo_TextView_ItemText_VerySmall = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int Proteo_TextView_ListHeadingNoSections = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int Proteo_TextView_ListHeadingSections = 2131165203;
			
			// aapt resource value: 0x7f070003
			public const int Proteo_TextView_MainHeading = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int Proteo_TextView_MessageContent = 2131165197;
			
			// aapt resource value: 0x7f070014
			public const int Proteo_TextView_Order = 2131165204;
			
			// aapt resource value: 0x7f070007
			public const int Proteo_TextView_PageTitle = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int Proteo_TextView_SectionContent = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int Proteo_TextView_SectionContentLarge = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int Proteo_TextView_SectionHeading = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int Proteo_TextView_SubHeading = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int Proteo_TextView_SubInformation = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int Proteo_TextView_VersionFooter = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int ProteoDialog = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int ProteoNoMargins = 2131165184;
			
			// aapt resource value: 0x7f070027
			public const int Theme_Splash = 2131165223;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int MvxListView_GroupItemTemplate = 2;
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
